<a href="https://colab.research.google.com/github/muhbasit/B/blob/main/Tensor_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf

In [10]:
# create 0-dimensional tensor
tensor0d = tf.constant(23)
print(tensor0d)
tensor0d = tf.constant([23])
print(tensor0d)

tf.Tensor(23, shape=(), dtype=int32)
tf.Tensor([23], shape=(1,), dtype=int32)


In [11]:
# create 1-dimensional tensor
tensor1d = tf.constant([23, 45, 69, 92])
print(tensor1d)

tf.Tensor([23 45 69 92], shape=(4,), dtype=int32)


In [23]:
# create 2-dimensional tensor
tensor2d = tf.constant([
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]
])
print(tensor2d)

tf.Tensor(
[[23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]], shape=(4, 4), dtype=int32)


In [ ]:
from google.colab import files

with open('example.txt', 'w') as f:
  f.write('some content')

files.download('example.txt')

In [24]:
# create 3-dimensional tensor
tensor3d = tf.constant([
[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]
])
print(tensor3d)

tf.Tensor(
[[[23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]]

 [[23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]]

 [[23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]]], shape=(3, 4, 4), dtype=int32)


In [25]:
# create 4-dimensional tensor
tensor4d = tf.constant([
[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]]
])
print(tensor4d)

tf.Tensor(
[[[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]], shape=(4, 3, 4, 4), dtype=int32)


In [26]:
# create 5-dimensional tensor
tensor5d = tf.constant([
[[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]]],

[[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]]],

[[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]]],

[[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]]]
])
print(tensor5d)

tf.Tensor(
[[[[[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]]


  [[[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]]


  [[[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]]


  [[[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]]]



 [[[[23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]
    [23 45 69 92]]

   [[23 45 69 92]

In [ ]:
# shape of tensors
print(tensor0d.shape)
print(tensor1d.shape)
print(tensor2d.shape)
print(tensor3d.shape)
print(tensor4d.shape)
print(tensor5d.shape)

(1,)
(4,)
(4, 4)
(3, 4, 4)
(4, 3, 4, 4)
(4, 4, 3, 4, 4)


In [ ]:
# dimensions of tensors
print(tensor0d.ndim)
print(tensor1d.ndim)
print(tensor2d.ndim)
print(tensor3d.ndim)
print(tensor4d.ndim)
print(tensor5d.ndim)

1
1
2
3
4
5


In [ ]:
, # DataType in Tensors
tensor4d = tf.constant([
[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]],

[[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]],

[[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92],
[23, 45, 69, 92]]]
], dtype=tf.float64)
print(tensor4d)

tf.Tensor(
[[[[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]

  [[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]

  [[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]]


 [[[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]

  [[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]

  [[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]]


 [[[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]

  [[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]

  [[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]]


 [[[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]

  [[23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]
   [23. 45. 69. 92.]]

  [[23. 45. 69. 92.]
   [23. 45. 69. 

In [ ]:
# Casted Tensor
cTensor = tf.cast(tensor4d, dtype=tf.int64)
print(cTensor)

tf.Tensor(
[[[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]], shape=(4, 3, 4, 4), dtype=int64)


In [ ]:
# Casted Tensor Bool
cTensor = tf.cast(tensor4d, dtype=tf.bool)
print(cTensor)

tf.Tensor(
[[[[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]]


 [[[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]]


 [[[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  T

In [ ]:
# Boolean Tensors
boolTensor1d = tf.constant([True, True, False])
print(boolTensor1d)
boolTensor2d = tf.constant([
[True, True, False],
[True, True, False],
[True, True, False]
])
print(boolTensor2d)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)
tf.Tensor(
[[ True  True False]
 [ True  True False]
 [ True  True False]], shape=(3, 3), dtype=bool)


In [ ]:
# String Tensors
sTensor1d = tf.constant("Hi Bilal")
print(sTensor1d)
sTensor2d = tf.constant(["Younas", "Basit", "Bilal"])
print(sTensor2d)

tf.Tensor(b'Hi Bilal', shape=(), dtype=string)
tf.Tensor([b'Younas' b'Basit' b'Bilal'], shape=(3,), dtype=string)


In [ ]:
# Convert NumPy array to Tensor
import numpy as np

npArr = np.array([23,69,92])
print(npArr)
npTensor = tf.convert_to_tensor(npArr)
print(npTensor)

[23 69 92]
tf.Tensor([23 69 92], shape=(3,), dtype=int64)


In [ ]:
# Identity Matrix/Tensor
iTensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(iTensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
# Identity Matrix/Tensor
iTensor = tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.int32,
    name=None
)
print(iTensor)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [ ]:
# Identity Matrix/Tensor
iTensor = tf.eye(
    num_rows=100,
    num_columns=100,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(iTensor)

tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]], shape=(100, 100), dtype=float32)


In [ ]:
# Filled Tensor
fTensor = tf.fill(
    10, 23
)
print(fTensor)
# 10 shows dimensions
# 23 shows value of elements

tf.Tensor([23 23 23 23 23 23 23 23 23 23], shape=(10,), dtype=int32)


In [ ]:
# Ones Tensors
oTensor = tf.ones(
    [23,23,23],
    dtype=tf.dtypes.float32,
    name=None
)
print(oTensor)

tf.Tensor(
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]

In [ ]:
# Ones Tensors
oTensor = tf.ones(
    tensor5d.shape,
    dtype=tf.dtypes.float32,
    name=None
)
print(oTensor)

tf.Tensor(
[[[[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]]



 [[[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]

In [ ]:
# One Like Tensor
olTensor = tf.ones_like(
    [23, 23], dtype=tf.int32, name=None
)
print(olTensor)

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [ ]:
# One Like Tensor
olTensor = tf.ones_like(
    tensor4d.shape, dtype=tf.int32, name=None
)
print(olTensor)

tf.Tensor([1 1 1 1], shape=(4,), dtype=int32)


In [ ]:
# Tensors Rank
print(tf.rank(tensor0d))
print(tf.rank(tensor1d))
print(tf.rank(tensor2d))
print(tf.rank(tensor3d))
print(tf.rank(tensor4d))
print(tf.rank(tensor5d))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
# Normal Distribution
nTensor = tf.random.normal(
    [3,3,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=5,
    name=None
)
print(nTensor)

tf.Tensor(
[[[-1.1780828  -0.7099414  -1.748158  ]
  [-0.49537227  0.24303888 -0.12631302]
  [-0.6639287  -0.49519837 -0.8939343 ]]

 [[-1.7965925   0.40887356 -1.2016594 ]
  [-1.0948371  -0.20036177  0.7267212 ]
  [-0.27756816  1.8058368   0.9972711 ]]

 [[-1.8598671  -1.1340102  -0.52885216]
  [-0.19741209  0.01328711 -0.28589568]
  [-0.4288976  -0.42463332  0.02154882]]], shape=(3, 3, 3), dtype=float32)


In [ ]:
# Uniform Distribution
uTensor = tf.random.uniform(
    [23, 23],
    low=0.0,
    high=1.0,
    validate_args=False,
    allow_nan_stats=True,
    name='Uniform'
)
print(uTensor)

TypeError: ignored

In [ ]:
sumTen = tensor0d + tensor0d
print(sumTen)

tf.Tensor([46], shape=(1,), dtype=int32)


In [ ]:
sumTen = tensor1d + tensor1d
print(sumTen)

tf.Tensor([ 46  90 138 184], shape=(4,), dtype=int32)


In [ ]:
sumTen = tensor2d + tensor2d
print(sumTen)

tf.Tensor(
[[ 46  90 138 184]
 [ 46  90 138 184]
 [ 46  90 138 184]
 [ 46  90 138 184]], shape=(4, 4), dtype=int32)


In [ ]:
sumTen = tensor3d + tensor3d
print(sumTen)

tf.Tensor(
[[[ 46  90 138 184]
  [ 46  90 138 184]
  [ 46  90 138 184]
  [ 46  90 138 184]]

 [[ 46  90 138 184]
  [ 46  90 138 184]
  [ 46  90 138 184]
  [ 46  90 138 184]]

 [[ 46  90 138 184]
  [ 46  90 138 184]
  [ 46  90 138 184]
  [ 46  90 138 184]]], shape=(3, 4, 4), dtype=int32)


In [ ]:
sumTen = tensor4d + tensor4d
print(sumTen)

tf.Tensor(
[[[[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]

  [[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]

  [[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]]


 [[[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]

  [[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]

  [[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]]


 [[[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]

  [[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]

  [[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]]]


 [[[ 46.  90. 138. 184.]
   [ 46.  90. 138. 184.]
   [ 46.  90. 1

In [ ]:
sumTen = tensor5d + tensor5d
print(sumTen)

tf.Tensor(
[[[[[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]

   [[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]

   [[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]]


  [[[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]

   [[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]

   [[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]]


  [[[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]

   [[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]

   [[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]]


  [[[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]]

   [[ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 184]
    [ 46  90 138 

In [ ]:
subTen = tensor5d - tensor5d
print(subTen)

tf.Tensor(
[[[[[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]]


  [[[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]]


  [[[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]]


  [[[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]]]



 [[[[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]]


  [[[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]]

   [[0 0 0 0]
    [0 0 0 0]
    [0 0 0 0]
    [0 

In [ ]:
mulTen = tensor5d * tensor5d
print(mulTen)

tf.Tensor(
[[[[[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]

   [[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]

   [[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]]


  [[[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]

   [[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]

   [[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]]


  [[[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]

   [[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]

   [[ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]
    [ 529 2025 4761 8464]]]


  [[[ 529 2025 4761 8464]
   

In [ ]:
divTen = tensor5d / tensor5d
print(divTen)

tf.Tensor(
[[[[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]]



 [[[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]

   [[1. 1. 1. 1.]

In [14]:
# Indexing 0-dimensional Tensor
tensor0d = tf.constant(23)
print(tensor0d)
#print(tensor0d[0])

tf.Tensor(23, shape=(), dtype=int32)


In [21]:
# Indexing 1-dimensional Tensor
print(tensor1d[3])
print(tensor1d[:])
print(tensor1d[0:3])
print(tensor1d[0:])
print(tensor1d[:3])
print(tensor1d[0:-1])
print(tensor1d[:-1])
print(tensor1d[3:-1])
print(tensor1d[0:4:2])
print(tensor1d[0:4:-1])

tf.Tensor(92, shape=(), dtype=int32)
tf.Tensor([23 45 69 92], shape=(4,), dtype=int32)
tf.Tensor([23 45 69], shape=(3,), dtype=int32)
tf.Tensor([23 45 69 92], shape=(4,), dtype=int32)
tf.Tensor([23 45 69], shape=(3,), dtype=int32)
tf.Tensor([23 45 69], shape=(3,), dtype=int32)
tf.Tensor([23 45 69], shape=(3,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([23 69], shape=(2,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)


In [33]:
# Indexing 2-dimensional Tensor
print(tensor2d[0:4,0:2])
print(tensor2d[0:,:2])
print(tensor2d[0:3,0:])
print(tensor2d[:,:])
print(tensor2d[:4,:])
print(tensor2d[:,0:2])
print(tensor2d[0,0:2])
print(tensor2d[0:4,])

tf.Tensor(
[[23 45]
 [23 45]
 [23 45]
 [23 45]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[23 45]
 [23 45]
 [23 45]
 [23 45]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[23 45]
 [23 45]
 [23 45]
 [23 45]], shape=(4, 2), dtype=int32)
tf.Tensor([23 45], shape=(2,), dtype=int32)
tf.Tensor(
[[23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]
 [23 45 69 92]], shape=(4, 4), dtype=int32)


In [36]:
# Indexing 3-dimensional Tensor
print(tensor3d[0:4,0:2,0:3])
print(tensor3d[0:,:2,:])
print(tensor3d[0:3,0:,0:2])
print(tensor3d[:,:,:])
print(tensor3d[:4,:,0:1])
print(tensor3d[:,0:2,:2])
print(tensor3d[0,0:2,1:])
print(tensor3d[0:4,2,1])

tf.Tensor(
[[[23 45 69]
  [23 45 69]]

 [[23 45 69]
  [23 45 69]]

 [[23 45 69]
  [23 45 69]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[23 45 69 92]
  [23 45 69 92]]

 [[23 45 69 92]
  [23 45 69 92]]

 [[23 45 69 92]
  [23 45 69 92]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(
[[[23 45]
  [23 45]
  [23 45]
  [23 45]]

 [[23 45]
  [23 45]
  [23 45]
  [23 45]]

 [[23 45]
  [23 45]
  [23 45]
  [23 45]]], shape=(3, 4, 2), dtype=int32)
tf.Tensor(
[[[23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]]

 [[23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]]

 [[23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]
  [23 45 69 92]]], shape=(3, 4, 4), dtype=int32)
tf.Tensor(
[[[23]
  [23]
  [23]
  [23]]

 [[23]
  [23]
  [23]
  [23]]

 [[23]
  [23]
  [23]
  [23]]], shape=(3, 4, 1), dtype=int32)
tf.Tensor(
[[[23 45]
  [23 45]]

 [[23 45]
  [23 45]]

 [[23 45]
  [23 45]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[45 69 92]
 [45 69 92]], shape=(2, 3), dtype=int32)
tf.Tensor([45 45 4

In [37]:
# Indexing 4-dimensional Tensor
print(tensor4d[0:4,0:2,0:3,:])
print(tensor4d[0:,:2,:,0:2])
print(tensor4d[0:3,0:,0:2,0:])
print(tensor4d[:,:,:,:])
print(tensor4d[:4,:,0:1,0:1])
print(tensor4d[:,0:2,:2,2])
print(tensor4d[0,0:2,1:,2:])
print(tensor4d[0:4,2,1,:2])

tf.Tensor(
[[[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]


 [[[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]
   [23 45 69 92]]]], shape=(4, 2, 3, 4), dtype=int32)
tf.Tensor(
[[[[23 45]
   [23 45]
   [23 45]
   [23 45]]

  [[23 45]
   [23 45]
   [23 45]
   [23 45]]]


 [[[23 45]
   [23 45]
   [23 45]
   [23 45]]

  [[23 45]
   [23 45]
   [23 45]
   [23 45]]]


 [[[23 45]
   [23 45]
   [23 45]
   [23 45]]

  [[23 45]
   [23 45]
   [23 45]
   [23 45]]]


 [[[23 45]
   [23 45]
   [23 45]
   [23 45]]

  [[23 45]
   [23 45]
   [23 45]
   [23 45]]]], shape=(4, 2, 4, 2), dtype=int32)
tf.Tensor(
[[[[23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [23 45 69 92]]

  [[23 45 69 92]
   [

In [38]:
# Indexing 5-dimensional Tensor
print(tensor5d[0:4,0:2,0:3,:,0:2])
print(tensor5d[0:,:2,:,0:2,0:3])
print(tensor5d[0:3,0:,0:2,0:,:3])
print(tensor5d[:,:,:,:,:])
print(tensor5d[:4,:,0:1,0:1,:])
print(tensor5d[:,0:2,:2,2,2])
print(tensor5d[0,0:2,1:,2:,2:])
print(tensor5d[0:4,2,1,:2,1:])

tf.Tensor(
[[[[[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]]


  [[[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]]]



 [[[[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]]


  [[[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]]]



 [[[[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]]


  [[[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 45]
    [23 45]
    [23 45]]]]



 [[[[23 45]
    [23 45]
    [23 45]
    [23 45]]

   [[23 45]
    [23 4